[build]
    publish = "public"
    command = "hugo --gc --minify --baseURL $URL"

[context.production.environment]
    HUGO_VERSION = "0.69.0"

[[redirects]]
  from = "https://utkarsh2102.netlify.com/*"
  to = "https://utkarsh2102.netlify.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://utkarsh2102.netlify.com/*"
  to = "https://utkarsh2102.netlify.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/projects/auto-mp-reviewer"
  to = "/projects/auto-mp-reviewer/"
  status = 301

[[redirects]]
  from = "/projects/auto-mp-reviewer/*"
  to = "https://utkarsh2102.github.io/auto-mp-reviewer/:splat"
  status = 200

[[redirects]]
  from = "/projects/ubuntu-image-inspector/*"
  to = "https://utkarsh2102.github.io/ubuntu-image-inspector/:splat"
  status = 200

[[redirects]]
  from = "/projects/auto-ffe-reviewer"
  to = "/projects/auto-ffe-reviewer/"
  status = 301

[[redirects]]
  from = "/projects/auto-ffe-reviewer/*"
  to = "https://utkarsh2102.github.io/auto-ffe-reviewer/:splat"
  status = 200

[[redirects]]
  from = "https://utkarsh2102.netlify.com/*"
  to = "https://utkarsh2102.netlify.com/:splat"
  status = 301
  force = true
